<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\Promoter;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        $promoters = Promoter::approved()->get();
        
        if ($promoters->isEmpty()) {
            $this->command->warn('No approved promoters found. Run PromoterSeeder first.');
            return;
        }

        $properties = [
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Belle Villa Moderne à Ouaga 2000',
                'title_en' => 'Beautiful Modern Villa in Ouaga 2000',
                'description_fr' => 'Magnifique villa moderne avec 4 chambres, piscine et jardin dans le quartier prisé de Ouaga 2000.',
                'description_en' => 'Magnificent modern villa with 4 bedrooms, swimming pool and garden in the sought-after Ouaga 2000 neighborhood.',
                'type' => 'house',
                'status' => 'available',
                'price' => 350000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 350000,
                'deposit_amount' => 350000,
                'advance_payment' => 100000,
                'commission_rate' => 10,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 300,
                'location' => 'Ouaga 2000',
                'address' => 'Avenue Kwame Nkrumah, Ouaga 2000',
                'latitude' => 12.3333,
                'longitude' => -1.5333,
                'images' => ['house1.jpg'],
                'featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'availability_status' => 'available',
            ],
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Appartement Spacieux Centre-Ville',
                'title_en' => 'Spacious City Center Apartment',
                'description_fr' => 'Appartement moderne de 3 chambres au cœur de Ouagadougou avec toutes les commodités.',
                'description_en' => 'Modern 3-bedroom apartment in the heart of Ouagadougou with all amenities.',
                'type' => 'apartment',
                'status' => 'available',
                'price' => 200000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 200000,
                'deposit_amount' => 200000,
                'advance_payment' => 50000,
                'commission_rate' => 10,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 120,
                'location' => 'Centre-Ville',
                'address' => 'Avenue de la Nation, Centre-Ville',
                'latitude' => 12.3714,
                'longitude' => -1.5197,
                'images' => ['apartment1.jpg'],
                'featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'availability_status' => 'available',
            ],
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Villa de Luxe Piscine',
                'title_en' => 'Luxury Villa with Pool',
                'description_fr' => 'Superbe villa avec piscine, jardin tropical et garage pour 3 voitures.',
                'description_en' => 'Stunning villa with pool, tropical garden and garage for 3 cars.',
                'type' => 'villa',
                'status' => 'available',
                'price' => 500000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 500000,
                'deposit_amount' => 500000,
                'advance_payment' => 150000,
                'commission_rate' => 10,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'area' => 400,
                'location' => 'Zone 1',
                'address' => 'Rue de l\'Indépendance, Zone 1',
                'latitude' => 12.3750,
                'longitude' => -1.5200,
                'images' => ['house2.jpg'],
                'featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => true,
                'availability_status' => 'available',
            ],
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Studio Moderne Étudiant',
                'title_en' => 'Modern Student Studio',
                'description_fr' => 'Studio meublé parfait pour étudiant ou jeune professionnel, proche université.',
                'description_en' => 'Furnished studio perfect for student or young professional, close to university.',
                'type' => 'studio',
                'status' => 'available',
                'price' => 80000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 80000,
                'deposit_amount' => 80000,
                'advance_payment' => 20000,
                'commission_rate' => 10,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'area' => 35,
                'location' => 'Gounghin',
                'address' => 'Rue des Étudiants, Gounghin',
                'latitude' => 12.3800,
                'longitude' => -1.5150,
                'images' => ['house2.jpg'],
                'featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'availability_status' => 'available',
            ],
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Duplex Standing Ouaga 2000',
                'title_en' => 'Luxury Duplex Ouaga 2000',
                'description_fr' => 'Magnifique duplex de standing avec terrasse panoramique et finitions haut de gamme.',
                'description_en' => 'Magnificent luxury duplex with panoramic terrace and high-end finishes.',
                'type' => 'apartment',
                'status' => 'available',
                'price' => 400000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 400000,
                'deposit_amount' => 400000,
                'advance_payment' => 120000,
                'commission_rate' => 10,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'area' => 200,
                'location' => 'Ouaga 2000',
                'address' => 'Boulevard Charles de Gaulle, Ouaga 2000',
                'latitude' => 12.3350,
                'longitude' => -1.5300,
                'images' => ['house2.jpg'],
                'featured' => true,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'availability_status' => 'available',
            ],
            [
                'promoter_id' => $promoters->random()->id,
                'title_fr' => 'Maison Familiale Zone 4',
                'title_en' => 'Family House Zone 4',
                'description_fr' => 'Maison confortable avec grand jardin, idéale pour famille nombreuse.',
                'description_en' => 'Comfortable house with large garden, ideal for large family.',
                'type' => 'house',
                'status' => 'available',
                'price' => 280000,
                'rental_frequency' => 'monthly',
                'monthly_rent' => 280000,
                'deposit_amount' => 280000,
                'advance_payment' => 80000,
                'commission_rate' => 10,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'area' => 180,
                'location' => 'Zone 4',
                'address' => 'Rue de la Paix, Zone 4',
                'latitude' => 12.3650,
                'longitude' => -1.5341,
                'images' => ['house2.jpg'],
                'featured' => false,
                'is_for_rent' => true,
                'is_for_sale' => false,
                'availability_status' => 'available',
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }

        $this->command->info('Created 6 properties with promoter assignments');
    }
}
